### ISSUE TITLE
Description downloading is unsafe

### ISSUE THREAD

**Issue by topaz** [ksmithut/advent-of-code#2] opened 2016-12-16 20:32 UTC
The method being used to download and rewrite descriptions is unsafe.  It relies on a specific class, which isn't guaranteed to be present, and does markup rewriting that appears to remove important information from the document.  I strongly recommend not relying on this kind of mechanism, and to instead use the presentation provided by the site itself.

**Comment by ksmithut** [comment] 2016-12-17 00:15
Agreed, would you suggest to just put a link to that day's description?

The use case I use for personally is that I don't like going back and forth between the problem description on the website and my code. I was doing it manually, but I also don't want to be the cause of extra unplanned requests to the website.

**Comment by topaz** [comment] 2016-12-17 02:08
A link is okay, or just assume the user already knows how to find the problem description. (if they don't, why are they using the module in the first place?)

As for your use case, just be aware that doing the transformation you're doing will lose meaning - things are emphasized and written in code formatting to make it clear what kinds of things are what.

**Comment by ksmithut** [comment] 2016-12-17 14:10
Fair point, relying on a screen scraping technique is rather unstable, but the transformations were based on markdown, and did a fairly accurate translation from your markup to markdown, so the meaning is somewhat there. That being said, I respect your wishes and I'll remove the description filling in. BTW, I'm going to deprecate the versions of this module that make these irresponsible requests.

**Comment by ksmithut** [comment] 2016-12-17 15:17
I've completely removed the pulling down and parsing of descriptions in version 2.0.0.

**Comment by ksmithut** [comment] 2016-12-20 04:07
@topaz Ah, I think I finally understand why you don't want automated pulling down of the description. Rest assured the feature has been removed. Feel free to close this issue if the solution is satisfactory.

**Closed as completed** 2016-12-20 04:09 UTC
